# Publish package on main branch if it's tagged with 'v*'

name: release & publish workflow

# Controls when the action will run.
on:
  push:
  pull_request:
    branches:
      - 'feature/*'
      - '!main'
#on:
#  # Triggers the workflow on push events but only for the master branch
#  push:
#    tags:
#      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  pull-requests: write
  contents: write
  repository-projects: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    name: Create Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: pdm-project/setup-pdm@v3
      - name: publish to PyPI
        run: pdm publish --repository testpypi
